server:
  # port: 443
  port: 8000
  # ssl:
  #   enabled: true
  #   key-store-password: noinjung90!
  #   key-store: classpath:keystore.p12
  #   key-store-type: PKCS12

# swagger:
#   ui:
#     scheme: https


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.26.2.118:8761/eureka

spring:
  application:
    name: ssafycnt-apigateway-service
  rabbitmq:
    host: 172.26.2.118
    port: 5672
    username: guest
    password: guest
  # zipkin:
  #   base-url: http://172.26.2.118:9411
  #   enabled: true
  # sleuth:
  #   sampler:
  #   probability: 1.0
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: ssafycnt-user-service
          uri: lb://SSAFYCNT-USER-SERVICE
          predicates:
            - Path=/ssafycnt-user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ssafycnt-user-service/(?<segment>.*), /$\{segment}
        - id: ssafycnt-news-service
          uri: lb://SSAFYCNT-NEWS-SERVICE
          predicates:
            - Path=/ssafycnt-news-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ssafycnt-news-service/(?<segment>.*), /$\{segment}
        - id: ssafycnt-trade-service
          uri: lb://SSAFYCNT-TRADE-SERVICE
          predicates:
            - Path=/ssafycnt-trade-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ssafycnt-trade-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

# springfox:
#   documentation:
#     swagger-ui:
#       enabled: true
#       url: https://ssafycnt.site/**/v3/api-docs