server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: ssafycnt-discovery-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # zipkin:
  #   base-url: http://172.26.2.118:9411
  #   enabled: true
  # sleuth:
  #   sampler:
  #   probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus
